
/* const listaProductos=[
    {
        id:"1",
        title:"FUNKO POP SPIDER-MAN TRAJE HEROE",
        price:"U$S 13,95",
        pictureURL:"https://www.funkotienda.com/wp-content/uploads/2019/05/figura-funko-spider-man-far-from-home-spider-man-traje-heroe.jpg",
        descripcion:"Comprar Funko Pop Spider-Man Traje Heroe, este Funko Pop de Spiderman Lejos de Casa es un producto oficial Funko ✔️, el cual está realizado en vinilo cuyo tamaño o formato es de 9 cm (Pop Estandar). Este muñeco Pop tiene el nº 468 de su colección de Spiderman Lejos de Casa 😍, su nombre original es Funko Pop Vinyl Spider-Man Hero Suit de la licencia Spiderman Far From Home.",
        category:"marvel",
        stock:"6",
    },
    {
        id:"2",
        title:"FUNKO POP CHUCKY",
        price:"U$S 15,95",
        pictureURL:"https://www.funkotienda.com/wp-content/uploads/2018/07/funko-pop-mu%C3%B1eco-diabolico-2-chucky.jpg",
        descripcion:"Comprar Funko Pop Chucky, este Funko Pop de El Muñeco diabólico 2 es un producto oficial Funko ✔️, el cual está realizado en vinilo cuyo tamaño o formato es de 9 cm (Pop Estandar). Este muñeco Pop tiene el nº 56 de su colección de El Muñeco diabólico 2 😍, su nombre original es Funko Pop Vinyl Chucky de la licencia Child´s Play 2.",
        category:"movie",
        stock:"2",
    },
    {
        id:"3",
        title:"FUNKO POP NEO (GITD)",
        price:"U$S 21,95",
        pictureURL:"https://www.funkotienda.com/wp-content/uploads/2022/02/Funko-Pop-The-Matrix-Neo-Exclusive.jpg",
        descripcion:"Comprar Funko Pop Neo (GITD), este Funko Pop de Matrix es un producto oficial Funko ✔️, el cual está realizado en vinilo cuyo tamaño o formato es de 9 cm (Pop Estandar). Este muñeco Pop tiene el nº 1172 de su colección de Matrix 😍, su nombre original es Funko Pop Vinyl Neo Glow in the Dark Exclusive de la licencia The Matrix.",
        category:"movie",
        stock:"3",
    },
    {
        id:"4",
        title:"FUNKO POP GOKU COMIENDO ESPAGUETIS",
        price:"U$S 24,95",
        pictureURL:"https://www.funkotienda.com/wp-content/uploads/2020/09/figura-funko-pop-dragon-ball-goku-eating-noodles.jpg",
        descripcion:"Comprar Funko Pop Goku Comiendo Espaguetis, este Funko Pop de Dragon Ball Z es un producto oficial Funko ✔️, el cual está realizado en vinilo cuyo tamaño o formato es de 9 cm (Pop Estandar). Este muñeco Pop tiene el nº 710 de su colección de Dragon Ball Z 😍, su nombre original es Funko Pop Vinyl Goku Eating Noodles de la licencia Dragon Ball Z.",
        category:"dragonball",
        stock:"4",
    },
    {
        id:"5",
        title:"FUNKO POP GHOST FLOCKED",
        price:"U$S 149,95",
        pictureURL:"https://www.funkotienda.com/wp-content/uploads/2019/12/figuras-funko-pop-juego-de-tronos-ghost-flocked.jpg",
        descripcion:"Comprar Funko Pop Ghost flocked, este Funko Pop de Juego de Tronos es un producto oficial Funko ✔️, el cual está realizado en vinilo cuyo tamaño o formato es de 9 cm (Pop Estandar). Este muñeco Pop tiene el nº 19 de su colección de Juego de Tronos 😍, su nombre original es Funko Pop Vinyl Ghost flocked de la licencia Game of Thrones.",
        category:"movie",
        stock:"1",
    },
    {
        id:"6",
        title:"FUNKO POP JOKER CON SOMBRERO 1989",
        price:"U$S 15,95",
        pictureURL:"https://www.funkotienda.com/wp-content/uploads/2020/04/figuras-funko-pop-batman-1989-the-joker-600x604.jpg",
        descripcion:"Comprar Funko Pop Joker con sombrero 1989, este Funko Pop de DC Comics Batman 1989 es un producto oficial Funko ✔️, el cual está realizado en vinilo cuyo tamaño o formato es de 9 cm (Pop Estandar). Este muñeco Pop tiene el nº 337 de su colección de DC Comics Batman 1989 😍, su nombre original es Funko Pop Vinyl Joker with Hat 1989 de la licencia DC Comics Batman 1989.",
        category:"dc",
        stock:"4",
    },
    {
        id:"7",
        title:"FUNKO POP BATMAN GRIM KNIGHT BATMAN EXCLUSIVO",
        price:"U$S 24,95",
        pictureURL:"https://www.funkotienda.com/wp-content/uploads/2020/10/figura-funko-pop-dc-comics-80-aniversario-batman-grim-knight.jpg",
        descripcion:"Comprar Funko Pop Batman Grim Knight Batman Exclusivo, este Funko Pop de DC Comics Batman 80th es un producto oficial Funko ✔️, el cual está realizado en vinilo cuyo tamaño o formato es de 9 cm (Pop Estandar). Este muñeco Pop tiene el nº 318 de su colección de DC Comics Batman 80th 😍, su nombre original es Funko Pop Vinyl Batman Grim Knight Batman Exclusive de la licencia DC Comics Batman 80th.",
        category:"dc",
        stock:"6",
    },
    {
        id:"8",
        title:"FUNKO POP THE PENGUIN",
        price:"U$S 19,95",
        pictureURL:"https://www.funkotienda.com/wp-content/uploads/2018/07/Funko-Pop-Batman-1966-The-Penguin.jpg",
        descripcion:"Comprar Funko Pop The Penguin, este Funko Pop de Batman 1966 es un producto oficial Funko ✔️, el cual está realizado en vinilo cuyo tamaño o formato es de 9 cm (Pop Estandar). Este muñeco Pop tiene el nº 184 de su colección de Batman 1966 😍, su nombre original es Funko Pop Vinyl The Penguin de la licencia Batman 1966.",
        category:"dc",
        stock:"4",
    },
    {
        id:"9",
        title:"FUNKO POP BOBA FETT EXCLUSIVO (SUPER SIZED 25 CM)",
        price:"U$S 29,95",
        pictureURL:"https://www.funkotienda.com/wp-content/uploads/2021/10/Funko-Pop-Star-Wars-Boba-Fett-Exclusive-25cm.jpg",
        descripcion:"Comprar Funko Pop Boba Fett Exclusivo (Super Sized 25 cm), este Funko Pop de Star Wars es un producto oficial Funko ✔️, el cual está realizado en vinilo cuyo tamaño o formato es de Super Sized (25 cm). Este muñeco Pop tiene el nº 367 de su colección de Star Wars 😍, su nombre original es Funko Pop Vinyl Boba Fett Exclusive 10 inch de la licencia Star Wars.",
        category:"starwars",
        stock:"2",
    },
    {
        id:"10",
        title:"FUNKO POP FIRST ORDER FLAMETROOPER",
        price:"U$S 13,95",
        pictureURL:"https://www.funkotienda.com/wp-content/uploads/2018/10/Funko-Pop-Star-Wars-Episode-VIII-The-Last-Jedi-First-Order-Flametrooper.jpg",
        descripcion:"Comprar Funko Pop First Order Flametrooper, este Funko Pop de Star Wars The Last Jedi es un producto oficial Funko ✔️, el cual está realizado en vinilo cuyo tamaño o formato es de 9 cm (Pop Estandar). Este muñeco Pop tiene el nº 68 de su colección de Star Wars The Last Jedi 😍, su nombre original es Funko Pop Vinyl First Order Flametrooper de la licencia Star Wars The Last Jedi.",
        category:"starwars",
        stock:"6",
    },
    {
        id:"11",
        title:"FUNKO POP DEADPOOL RAINBOW",
        price:"U$S 14,95",
        pictureURL:"https://www.funkotienda.com/wp-content/uploads/2021/05/Funko-Pop-Marvel-Pride-Deadpool-Rainbow.jpg",
        descripcion:"Comprar Funko Pop Deadpool Rainbow, este Funko Pop de Marvel Pride es un producto oficial Funko ✔️, el cual está realizado en vinilo cuyo tamaño o formato es de 9 cm (Pop Estandar). Este muñeco Pop tiene el nº 320 de su colección de Marvel Pride 😍, su nombre original es Funko Pop Vinyl Deadpool Rainbow de la licencia Marvel Pride.",
        category:"marvel",
        stock:"2",
    },
    {
        id:"12",
        title:"FUNKO POP IRON MAN (ENSAMBLAR)",
        price:"U$S 29,95",
        pictureURL:"https://www.funkotienda.com/wp-content/uploads/2022/01/Funko-Pop-deluxe-marvel-los-vengadores-iron-man-assemble.jpg",
        descripcion:"Comprar Funko Pop Iron Man (Ensamblar), este Funko Pop de Los Vengadores es un producto oficial Funko ✔️, el cual está realizado en vinilo cuyo tamaño o formato es de Super Sized (15 cm). Este muñeco Pop tiene el nº 584 de su colección de Los Vengadores 😍, su nombre original es Funko Pop Vinyl Iron Man Assemble de la licencia Avengers.",
        category:"marvel",
        stock:"1",
    },
    
]

export const getProductos = new Promise((resolve, reject)=>{
    
        resolve(listaProductos)
  }); */